# Generated by Django 6.0.6 on 2026-06-28 04:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe empezar con 9 y tener exactamente 9 dígitos.', regex='^9\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener exactamente 8 números.', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe empezar con 9 y tener exactamente 9 dígitos.', regex='^9\\d{8}$')]),
        ),
    ]
