# Generated by Django 6.0.6 on 2026-06-29 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_doctor_telefono_alter_paciente_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='apellidos',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nombres',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')]),
        ),
    ]
