# Generated by Django 6.0.6 on 2026-07-05 01:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_doctor_apellidos_alter_doctor_nombres_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')])),
                ('apellidos', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')])),
                ('rol', models.CharField(choices=[('RECEPCION', 'Recepción'), ('GERENTE', 'Gerente'), ('ADMIN', 'Administrador')], max_length=15)),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe empezar con 9 y tener exactamente 9 dígitos.', regex='^9\\d{8}$')])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
