# Generated by Django 6.0.6 on 2026-07-12 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_doctor_usuario_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='rol',
            field=models.CharField(choices=[('RECEPCION', 'Recepción'), ('ADMIN', 'Administrador')], max_length=15),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('indicaciones', models.TextField(blank=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='clinica.consulta')),
            ],
        ),
    ]
