# Generated by Django 6.0.6 on 2026-07-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_alter_personal_rol_receta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='medicamentos',
        ),
    ]
