# Generated by Django 6.0.6 on 2026-07-13 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_remove_consulta_medicamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='consulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='clinica.consulta'),
        ),
    ]
